// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: kitchen.proto

package kitchenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId int64 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *GetBookingsRequest) Reset() {
	*x = GetBookingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsRequest) ProtoMessage() {}

func (x *GetBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingsRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookingsRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GetBookingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bookings []*Booking `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
}

func (x *GetBookingsResponse) Reset() {
	*x = GetBookingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsResponse) ProtoMessage() {}

func (x *GetBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsResponse.ProtoReflect.Descriptor instead.
func (*GetBookingsResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type Booking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingId int64 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	KitchenId int64 `protobuf:"varint,2,opt,name=kitchen_id,json=kitchenId,proto3" json:"kitchen_id,omitempty"`
}

func (x *Booking) Reset() {
	*x = Booking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{2}
}

func (x *Booking) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Booking) GetKitchenId() int64 {
	if x != nil {
		return x.KitchenId
	}
	return 0
}

type UnPublishKitchenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId int64 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *UnPublishKitchenRequest) Reset() {
	*x = UnPublishKitchenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnPublishKitchenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPublishKitchenRequest) ProtoMessage() {}

func (x *UnPublishKitchenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPublishKitchenRequest.ProtoReflect.Descriptor instead.
func (*UnPublishKitchenRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_proto_rawDescGZIP(), []int{3}
}

func (x *UnPublishKitchenRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

var File_kitchen_proto protoreflect.FileDescriptor

var file_kitchen_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x47, 0x0a, 0x07, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65,
	0x6e, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x17, 0x55, 0x6e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x32, 0xaf, 0x01, 0x0a, 0x0e, 0x4b, 0x69,
	0x74, 0x63, 0x68, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x21,
	0x47, 0x65, 0x74, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x19,
	0x55, 0x6e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e,
	0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x55, 0x6e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2d, 0x5a, 0x2b, 0x61,
	0x70, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6b, 0x69,
	0x74, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e,
	0x3b, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_kitchen_proto_rawDescOnce sync.Once
	file_kitchen_proto_rawDescData = file_kitchen_proto_rawDesc
)

func file_kitchen_proto_rawDescGZIP() []byte {
	file_kitchen_proto_rawDescOnce.Do(func() {
		file_kitchen_proto_rawDescData = protoimpl.X.CompressGZIP(file_kitchen_proto_rawDescData)
	})
	return file_kitchen_proto_rawDescData
}

var file_kitchen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kitchen_proto_goTypes = []interface{}{
	(*GetBookingsRequest)(nil),      // 0: GetBookingsRequest
	(*GetBookingsResponse)(nil),     // 1: GetBookingsResponse
	(*Booking)(nil),                 // 2: Booking
	(*UnPublishKitchenRequest)(nil), // 3: UnPublishKitchenRequest
	(*emptypb.Empty)(nil),           // 4: google.protobuf.Empty
}
var file_kitchen_proto_depIdxs = []int32{
	2, // 0: GetBookingsResponse.bookings:type_name -> Booking
	0, // 1: KitchenService.GetKitchenActiveBookingsByOwnerId:input_type -> GetBookingsRequest
	3, // 2: KitchenService.UnPublishKitchenByOwnerId:input_type -> UnPublishKitchenRequest
	1, // 3: KitchenService.GetKitchenActiveBookingsByOwnerId:output_type -> GetBookingsResponse
	4, // 4: KitchenService.UnPublishKitchenByOwnerId:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kitchen_proto_init() }
func file_kitchen_proto_init() {
	if File_kitchen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kitchen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Booking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnPublishKitchenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kitchen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kitchen_proto_goTypes,
		DependencyIndexes: file_kitchen_proto_depIdxs,
		MessageInfos:      file_kitchen_proto_msgTypes,
	}.Build()
	File_kitchen_proto = out.File
	file_kitchen_proto_rawDesc = nil
	file_kitchen_proto_goTypes = nil
	file_kitchen_proto_depIdxs = nil
}
