// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/generation/users/v1/protos/users.proto

package service

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_generation_users_v1_protos_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generation_users_v1_protos_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_generation_users_v1_protos_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login            string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailAccess      bool                   `protobuf:"varint,4,opt,name=email_access,json=emailAccess,proto3" json:"email_access,omitempty"`
	Role             int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	IsDeleted        bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	BlockTypeId      int32                  `protobuf:"varint,8,opt,name=block_type_id,json=blockTypeId,proto3" json:"block_type_id,omitempty"`
	ForeverFlag      bool                   `protobuf:"varint,9,opt,name=forever_flag,json=foreverFlag,proto3" json:"forever_flag,omitempty"`
	UnblockDate      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=unblock_date,json=unblockDate,proto3" json:"unblock_date,omitempty"`
	BlockTitle       string                 `protobuf:"bytes,11,opt,name=block_title,json=blockTitle,proto3" json:"block_title,omitempty"`
	BlockDescription string                 `protobuf:"bytes,12,opt,name=block_description,json=blockDescription,proto3" json:"block_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_generation_users_v1_protos_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generation_users_v1_protos_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_generation_users_v1_protos_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetEmailAccess() bool {
	if x != nil {
		return x.EmailAccess
	}
	return false
}

func (x *GetUserResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GetUserResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *GetUserResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *GetUserResponse) GetBlockTypeId() int32 {
	if x != nil {
		return x.BlockTypeId
	}
	return 0
}

func (x *GetUserResponse) GetForeverFlag() bool {
	if x != nil {
		return x.ForeverFlag
	}
	return false
}

func (x *GetUserResponse) GetUnblockDate() *timestamppb.Timestamp {
	if x != nil {
		return x.UnblockDate
	}
	return nil
}

func (x *GetUserResponse) GetBlockTitle() string {
	if x != nil {
		return x.BlockTitle
	}
	return ""
}

func (x *GetUserResponse) GetBlockDescription() string {
	if x != nil {
		return x.BlockDescription
	}
	return ""
}

var File_api_generation_users_v1_protos_users_proto protoreflect.FileDescriptor

const file_api_generation_users_v1_protos_users_proto_rawDesc = "" +
	"\n" +
	"*api/generation/users/v1/protos/users.proto\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb2\x03\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\femail_access\x18\x04 \x01(\bR\vemailAccess\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\"\n" +
	"\rblock_type_id\x18\b \x01(\x05R\vblockTypeId\x12!\n" +
	"\fforever_flag\x18\t \x01(\bR\vforeverFlag\x12=\n" +
	"\funblock_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vunblockDate\x12\x1f\n" +
	"\vblock_title\x18\v \x01(\tR\n" +
	"blockTitle\x12+\n" +
	"\x11block_description\x18\f \x01(\tR\x10blockDescription2F\n" +
	"\x12UserProfileService\x120\n" +
	"\vGetUserById\x12\x0f.GetUserRequest\x1a\x10.GetUserResponseB&Z$api/generation/users/v1/users;userpbb\x06proto3"

var (
	file_api_generation_users_v1_protos_users_proto_rawDescOnce sync.Once
	file_api_generation_users_v1_protos_users_proto_rawDescData []byte
)

func file_api_generation_users_v1_protos_users_proto_rawDescGZIP() []byte {
	file_api_generation_users_v1_protos_users_proto_rawDescOnce.Do(func() {
		file_api_generation_users_v1_protos_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_generation_users_v1_protos_users_proto_rawDesc), len(file_api_generation_users_v1_protos_users_proto_rawDesc)))
	})
	return file_api_generation_users_v1_protos_users_proto_rawDescData
}

var file_api_generation_users_v1_protos_users_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_generation_users_v1_protos_users_proto_goTypes = []any{
	(*GetUserRequest)(nil),        // 0: GetUserRequest
	(*GetUserResponse)(nil),       // 1: GetUserResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_generation_users_v1_protos_users_proto_depIdxs = []int32{
	2, // 0: GetUserResponse.deleted_at:type_name -> google.protobuf.Timestamp
	2, // 1: GetUserResponse.unblock_date:type_name -> google.protobuf.Timestamp
	0, // 2: UserProfileService.GetUserById:input_type -> GetUserRequest
	1, // 3: UserProfileService.GetUserById:output_type -> GetUserResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_generation_users_v1_protos_users_proto_init() }
func file_api_generation_users_v1_protos_users_proto_init() {
	if File_api_generation_users_v1_protos_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_generation_users_v1_protos_users_proto_rawDesc), len(file_api_generation_users_v1_protos_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_generation_users_v1_protos_users_proto_goTypes,
		DependencyIndexes: file_api_generation_users_v1_protos_users_proto_depIdxs,
		MessageInfos:      file_api_generation_users_v1_protos_users_proto_msgTypes,
	}.Build()
	File_api_generation_users_v1_protos_users_proto = out.File
	file_api_generation_users_v1_protos_users_proto_goTypes = nil
	file_api_generation_users_v1_protos_users_proto_depIdxs = nil
}
